name: Build OLLVM NDK Toolchain

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Patched AOSP Toolchain
    runs-on: ubuntu-latest

    steps:
      - name: Checkout OLLVM NDK Patcher repository
        uses: actions/checkout@v4
        with:
          repository: codetronik/ollvm-ndk
          ref: r23c
          path: patcher

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential ca-certificates ccache cmake curl git ninja-build python3 bison

      - name: Install libffi6 dependency
        run: |
          curl -LO http://archive.ubuntu.com/ubuntu/pool/main/libf/libffi/libffi6_3.2.1-8_amd64.deb
          sudo dpkg -i libffi6_3.2.1-8_amd64.deb

      - name: Install latest repo launcher (v2.58)
        run: |
          mkdir -p ~/.local/bin
          curl -s "https://gerrit.googlesource.com/git-repo/+/refs/tags/v2.58?format=TEXT" | base64 -d > ~/.local/bin/repo
          chmod +x ~/.local/bin/repo
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          export PATH="$HOME/.local/bin:$PATH"
          repo --version

      - name: Configure Git for Repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Initialize and Sync AOSP Toolchain Source
        run: |
          mkdir aosp_toolchain_src
          cd aosp_toolchain_src
          
          # B1. Init repo
          repo init -u https://android.googlesource.com/platform/manifest -b llvm-toolchain
          
          # B2. Dùng manifest tùy chỉnh
          cp ../patcher/manifest_8481493.xml .repo/manifests/
          repo init -m manifest_8481493.xml

          # B3. Đồng bộ source (đã có --depth=1)
          repo sync -c -j$(nproc) --no-clone-bundle --no-tags --depth=1

      - name: Apply OLLVM patches
        run: |
          cp -rf patcher/llvm aosp_toolchain_src/toolchain/llvm-project/

      - name: Run the build script
        timeout-minutes: 360
        working-directory: ./aosp_toolchain_src
        run: python3 toolchain/llvm_android/build.py --no-build=windows --skip-package --skip-runtimes

      - name: Package the toolchain
        run: |
          cd aosp_toolchain_src/out/install/linux-x86
          tar -cJf ../../../toolchain.tar.xz .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: patched-aosp-toolchain
          path: aosp_toolchain_src/toolchain.tar.xz
          retention-days: 7
