name: Build OLLVM NDK Toolchain
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Patched AOSP Toolchain
    runs-on: ubuntu-22.04
    env:
      TMPDIR: ${{ github.workspace }}/.tmp
      CCACHE_DIR: ${{ github.workspace }}/.ccache

    steps:
      # 0) Mở rộng dung lượng trống trên runner
      - name: Maximize free space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          temp-reserve-mb: 512
          swap-size-mb: 1
          remove-android: true
          remove-dotnet: true
          remove-haskell: true
          remove-docker-images: true

      - name: Show free space (before)
        run: df -h

      # 1) Checkout repo patcher (r23c)
      - name: Checkout OLLVM NDK Patcher repository
        uses: actions/checkout@v4
        with:
          repository: codetronik/ollvm-ndk
          ref: r23c
          path: patcher
          fetch-depth: 1

      # 2) Cài deps tối thiểu
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential ca-certificates cmake curl git ninja-build \
            python3 bison ccache xz-utils rsync jq
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*

      # 3) (tuỳ môi trường) libffi6 cho script cũ
      - name: Install libffi6 dependency
        run: |
          curl -sSLO http://archive.ubuntu.com/ubuntu/pool/main/libf/libffi/libffi6_3.2.1-8_amd64.deb
          sudo dpkg -i libffi6_3.2.1-8_amd64.deb || true
          rm -f libffi6_3.2.1-8_amd64.deb

      # 4) Repo tool mới nhất (tránh bản quá cũ)
      - name: Install latest repo tool
        run: |
          sudo curl -sSL https://storage.googleapis.com/git-repo-downloads/repo -o /usr/local/bin/repo
          sudo chmod +x /usr/local/bin/repo
          repo --version || true

      # 5) Cấu hình Git và thư mục tạm/cache nằm trong workspace
      - name: Configure Git & prepare dirs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          mkdir -p "$TMPDIR" "$CCACHE_DIR"

      # 6) repo init + sync (partial clone blobless; nếu fail thì fallback)
      - name: Initialize and Sync AOSP Toolchain Source
        run: |
          set -euxo pipefail
          mkdir aosp_toolchain_src
          cd aosp_toolchain_src
          repo init -u https://android.googlesource.com/platform/manifest -b llvm-toolchain
          cp ../patcher/manifest_8481493.xml .repo/manifests/
          repo init -m manifest_8481493.xml

          if repo sync -c \
              --no-clone-bundle \
              --no-tags \
              --optimized-fetch \
              --prune \
              --partial-clone \
              --clone-filter=blob:none \
              -j"$(nproc)"; then
            echo "Partial clone OK"
          else
            echo "Partial clone failed; fallback to normal slim sync"
            repo sync -c \
              --no-clone-bundle \
              --no-tags \
              --optimized-fetch \
              --prune \
              -j"$(nproc)"
          fi

      # 7) Overlay OLLVM (KHÔNG đè nguyên cây llvm/)
      - name: Apply OLLVM overlay (non-destructive)
        run: |
          set -euxo pipefail
          # Chỉ overlay thư mục Obfuscation (lib + include)
          rsync -a patcher/llvm/lib/Transforms/Obfuscation/ \
            aosp_toolchain_src/toolchain/llvm-project/llvm/lib/Transforms/Obfuscation/
          rsync -a patcher/llvm/include/llvm/Transforms/Obfuscation/ \
            aosp_toolchain_src/toolchain/llvm-project/llvm/include/llvm/Transforms/Obfuscation/

          # Bổ sung add_subdirectory(Obfuscation) nếu chưa có
          T="aosp_toolchain_src/toolchain/llvm-project/llvm/lib/Transforms/CMakeLists.txt"
          if ! grep -q 'add_subdirectory(Obfuscation)' "$T"; then
            echo 'add_subdirectory(Obfuscation)' >> "$T"
          fi

      # 8) Build tối thiểu (bỏ windows/darwin, skip package & runtimes)
      - name: Build AOSP LLVM (minimal)
        timeout-minutes: 360
        working-directory: ./aosp_toolchain_src
        run: |
          set -euxo pipefail
          ccache --max-size=2G || true
          python3 toolchain/llvm_android/build.py \
            --no-build=windows \
            --skip-package \
            --skip-runtimes
          ccache -s || true
          du -sh out || true
          df -h

      # 9) Dọn build tree: chỉ giữ install/linux-x86
      - name: Prune build outputs (keep install only)
        working-directory: ./aosp_toolchain_src
        run: |
          set -euxo pipefail
          # Giữ mỗi out/install
          find out -mindepth 1 -maxdepth 1 ! -name install -exec rm -rf {} +
          # Giữ linux-x86 bên trong install (nếu có multi-host)
          if [ -d out/install ]; then
            find out/install -mindepth 1 -maxdepth 1 ! -name linux-x86 -exec rm -rf {} + || true
          fi
          du -sh out || true
          df -h

      # 10) Đóng gói (xz -9e)
      - name: Package the toolchain
        working-directory: ./aosp_toolchain_src/out/install/linux-x86
        run: |
          set -euxo pipefail
          tar -I 'xz -9e' -cf ../../../toolchain.tar.xz .
          du -sh ../../../toolchain.tar.xz
          df -h

      # 11) Upload artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: patched-aosp-toolchain
          path: aosp_toolchain_src/out/toolchain.tar.xz
          retention-days: 7

      - name: Show free space (after)
        run: df -h
